# ============================================================
# zabbix_agent_apcupsd.conf — Zabbix Agent UserParameters for APC UPS
# Copyright (C) 2024-2025 PlurumTech.com
# Licensed under GNU GPL v3 — https://www.gnu.org/licenses/gpl-3.0.html
# ============================================================

#apcupsd params
UserParameter=apcups.volts,cat /var/log/apcupsd.status|grep LINEV|awk '{print $3}'
UserParameter=apcups.charge,cat /var/log/apcupsd.status|grep BCHARGE|awk '{print $3}'
UserParameter=apcups.load,cat /var/log/apcupsd.status|grep LOADPCT|awk '{print $3}'
UserParameter=apcups.name,cat /var/log/apcupsd.status|grep MODEL|awk '{print $3" "$4}'
UserParameter=apcups.status,cat /var/log/apcupsd.status|grep STATUS|awk '{print $3}'
UserParameter=apcups.lasterr,cat /var/log/apcupsd.status|grep LASTXFER|awk -F: '{print $2}'
